### ISSUE TITLE
After Update to 0.110 card isnt working anymore

### ISSUE THREAD

**Issue by Flipsoo** [bradcrc/color-lite-card#3]
Hey there,
after i updated to Hass.IO 0.110 the card doesnt work anymore. constantly getting "undefined is not an object (evaluating hass.states)". Do i have something misconfigured? before 0.110 everything was working fine and i really liked your card - really a good job you done there =)=)

Greetings=)

**Comment by bradcrc** [comment]
bummer.  looks like 110 broke both these custom cards.
 
that sucks.  I'll update the docs to let everyone know.   

thanks for letting me know.

**Comment by belladieg** [comment]
hello your card is very cool, are you going to correct the problem?

would be great

**Comment by bradcrc** [comment]
Spent a few hours looking into this today.   It appears that the card works fine on its own in lovelace.   It only generates this error when it's used inside of a picture elements card.
 
It appears the hass.states is not being passed from the picture elements container.    I'm guessing this is a defect in the picture elements card, since the custom now playing card works outside of picture elements,  and [the documentation on custom cards ](https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-card/) shows the exact code which is used by this custom card.
 
It does not appear at this time that there is anything that can be done from this card since the issue is external.  Hopefully they will either fix this in the picture elements card, or update the documentation to show a different way to pull the states from an entity when referenced from inside picture elements.

These cards are very simple javascript directly based on the sample custom cards,  feel free to let me know if you have any other suggestions, otherwise it doesn't appear that we can do anything from our side at this time.

**Comment by gxzgithub** [comment]
updated to Hass.IO 0.110 ,only open with Microsot Edge it's seems ok!

**Comment by salvasacie** [comment]
in version 0.110.2 it is fully functional.
